import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),("storefront","0001_initial"),("organizations","0002_align_index_names")]
    operations=[
        migrations.CreateModel(name="CheckoutSession",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("draft","Draft"),("placed","Placed"),("expired","Expired"),("cancelled","Cancelled")],db_index=True,default="draft",max_length=20)),("shipping_name",models.CharField(blank=True,max_length=180)),("shipping_phone",models.CharField(blank=True,max_length=50)),("shipping_email",models.EmailField(blank=True,max_length=254)),("shipping_address1",models.CharField(blank=True,max_length=255)),("shipping_address2",models.CharField(blank=True,max_length=255)),("shipping_city",models.CharField(blank=True,max_length=120)),("shipping_region",models.CharField(blank=True,max_length=120)),("shipping_country",models.CharField(default="EG",max_length=2)),("postal_code",models.CharField(blank=True,max_length=30)),("subtotal",models.DecimalField(decimal_places=2,default=0,max_digits=12)),("shipping_amount",models.DecimalField(decimal_places=2,default=0,max_digits=12)),("discount_amount",models.DecimalField(decimal_places=2,default=0,max_digits=12)),("total",models.DecimalField(decimal_places=2,default=0,max_digits=12)),("currency",models.CharField(default="EGP",max_length=3)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("placed_at",models.DateTimeField(blank=True,null=True)),("customer",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="checkout_sessions",to=settings.AUTH_USER_MODEL)),("studio_project",models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name="checkout_session",to="storefront.studioproject"))],options={"ordering":("-updated_at",)}),
        migrations.CreateModel(name="CustomerOrder",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("number",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("status",models.CharField(choices=[("pending_payment","Pending payment"),("confirmed","Confirmed"),("payment_failed","Payment failed"),("cancelled","Cancelled"),("refunded","Refunded")],db_index=True,default="pending_payment",max_length=24)),("payment_method",models.CharField(choices=[("cod","Cash on Delivery"),("paymob","Paymob"),("stripe","Stripe")],max_length=20)),("subtotal",models.DecimalField(decimal_places=2,max_digits=12)),("shipping_amount",models.DecimalField(decimal_places=2,default=0,max_digits=12)),("discount_amount",models.DecimalField(decimal_places=2,default=0,max_digits=12)),("total",models.DecimalField(decimal_places=2,max_digits=12)),("currency",models.CharField(max_length=3)),("shipping_snapshot",models.JSONField(default=dict)),("confirmed_at",models.DateTimeField(blank=True,null=True)),("cancelled_at",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("checkout",models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name="order",to="checkout.checkoutsession")),("customer",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="customer_orders",to=settings.AUTH_USER_MODEL)),("designer_organization",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="store_orders",to="organizations.organization"))],options={"ordering":("-created_at",),"indexes":[models.Index(fields=["customer","status"],name="order_customer_status_idx")]}),
        migrations.CreateModel(name="OrderItem",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("sku",models.CharField(max_length=120)),("title",models.CharField(max_length=220)),("size",models.CharField(blank=True,max_length=40)),("color_name",models.CharField(blank=True,max_length=80)),("unit_price",models.DecimalField(decimal_places=2,max_digits=12)),("quantity",models.PositiveIntegerField()),("line_total",models.DecimalField(decimal_places=2,max_digits=12)),("customization_snapshot",models.JSONField(blank=True,default=dict)),("order",models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name="item",to="checkout.customerorder")),("store_product",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="order_items",to="storefront.storeproduct")),("studio_project",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="order_items",to="storefront.studioproject")),("variant",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="order_items",to="storefront.productvariant"))]),
        migrations.CreateModel(name="PaymentAttempt",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("provider",models.CharField(choices=[("cod","Cash on Delivery"),("paymob","Paymob"),("stripe","Stripe")],max_length=20)),("status",models.CharField(choices=[("pending","Pending"),("requires_action","Requires action"),("succeeded","Succeeded"),("failed","Failed"),("cancelled","Cancelled"),("refunded","Refunded")],db_index=True,default="pending",max_length=24)),("amount",models.DecimalField(decimal_places=2,max_digits=12)),("currency",models.CharField(max_length=3)),("idempotency_key",models.CharField(max_length=80,unique=True)),("provider_reference",models.CharField(blank=True,db_index=True,max_length=180)),("redirect_url",models.URLField(blank=True)),("provider_payload",models.JSONField(blank=True,default=dict)),("failure_code",models.CharField(blank=True,max_length=80)),("failure_message",models.CharField(blank=True,max_length=255)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("completed_at",models.DateTimeField(blank=True,null=True)),("order",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="payment_attempts",to="checkout.customerorder"))],options={"ordering":("-created_at",)}),
        migrations.CreateModel(name="PaymentWebhookEvent",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("provider",models.CharField(choices=[("paymob","Paymob"),("stripe","Stripe")],max_length=20)),("event_id",models.CharField(max_length=180)),("payload_hash",models.CharField(max_length=64)),("processed",models.BooleanField(default=False)),("processing_error",models.CharField(blank=True,max_length=255)),("received_at",models.DateTimeField(auto_now_add=True)),("processed_at",models.DateTimeField(blank=True,null=True))],options={"ordering":("-received_at",)}),
        migrations.AddConstraint(model_name="paymentwebhookevent",constraint=models.UniqueConstraint(fields=("provider","event_id"),name="unique_payment_webhook_event")),
    ]
