name: fabinzi_customer_app
description: FABINZI Customer application for Android and iOS.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.13.0 <4.0.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
