from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("organizations", "0002_align_index_names"), ("media", "0002_rename_media_asset_index")]
    operations = [
        migrations.CreateModel(name="GarmentDesign", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=220)),("description",models.TextField(blank=True)),("category",models.CharField(blank=True,max_length=120)),("status",models.CharField(choices=[("draft","Draft"),("in_review","In technical review"),("revision_required","Revision required"),("approved","Approved"),("rejected","Rejected"),("archived","Archived")],default="draft",max_length=24)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="created_garment_designs",to=settings.AUTH_USER_MODEL)),("organization",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="garment_designs",to="organizations.organization"))],options={"ordering":("-updated_at",)}),
        migrations.CreateModel(name="GarmentDesignVersion", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("version_number",models.PositiveIntegerField()),("status",models.CharField(choices=[("draft","Draft"),("submitted","Submitted"),("revision_required","Revision required"),("approved","Approved"),("rejected","Rejected")],default="draft",max_length=24)),("summary",models.CharField(blank=True,max_length=255)),("base_material",models.CharField(blank=True,max_length=255)),("construction_notes",models.TextField(blank=True)),("technical_specs",models.JSONField(blank=True,default=dict)),("created_at",models.DateTimeField(auto_now_add=True)),("submitted_at",models.DateTimeField(blank=True,null=True)),("reviewed_at",models.DateTimeField(blank=True,null=True)),("review_notes",models.TextField(blank=True)),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="created_design_versions",to=settings.AUTH_USER_MODEL)),("design",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="versions",to="design.garmentdesign")),("reviewed_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="reviewed_design_versions",to=settings.AUTH_USER_MODEL))],options={"ordering":("-version_number",)}),
        migrations.AddConstraint(model_name="garmentdesignversion",constraint=models.UniqueConstraint(fields=("design","version_number"),name="unique_design_version_number")),
        migrations.CreateModel(name="SizeChartRow", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("size_label",models.CharField(max_length=40)),("measurements",models.JSONField(default=dict)),("notes",models.CharField(blank=True,max_length=255)),("sort_order",models.PositiveIntegerField(default=0)),("version",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="size_rows",to="design.garmentdesignversion"))],options={"ordering":("sort_order","id")}),
        migrations.AddConstraint(model_name="sizechartrow",constraint=models.UniqueConstraint(fields=("version","size_label"),name="unique_version_size_label")),
        migrations.CreateModel(name="DecorationZone", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=120)),("method",models.CharField(choices=[("print","Print"),("embroidery","Embroidery"),("both","Print or embroidery")],default="both",max_length=20)),("placement",models.JSONField(default=dict,help_text="Normalized placement/geometry definition.")),("max_width_mm",models.DecimalField(blank=True,decimal_places=2,max_digits=8,null=True)),("max_height_mm",models.DecimalField(blank=True,decimal_places=2,max_digits=8,null=True)),("notes",models.TextField(blank=True)),("version",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="decoration_zones",to="design.garmentdesignversion"))],options={"ordering":("id",)}),
        migrations.AddConstraint(model_name="decorationzone",constraint=models.UniqueConstraint(fields=("version","name"),name="unique_version_decoration_zone")),
        migrations.CreateModel(name="DesignAsset", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("kind",models.CharField(choices=[("product_image","Product image"),("pattern","Pattern"),("tech_pack","Tech pack"),("3d","3D asset"),("technical","Technical file")],max_length=24)),("label",models.CharField(blank=True,max_length=180)),("created_at",models.DateTimeField(auto_now_add=True)),("media_asset",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="design_assets",to="media.mediaasset")),("version",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="assets",to="design.garmentdesignversion"))]),
        migrations.CreateModel(name="TechnicalReview", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("decision",models.CharField(choices=[("approved","Approved"),("revision_required","Revision required"),("rejected","Rejected")],max_length=24)),("notes",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("reviewer",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="garment_technical_reviews",to=settings.AUTH_USER_MODEL)),("version",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="reviews",to="design.garmentdesignversion"))],options={"ordering":("-created_at",)}),
    ]
