from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("design", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="garmentdesign",
            name="symbolic_ref",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="garmentdesignversion",
            name="symbolic_ref",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="garmentdesignversion",
            name="technical_schema_version",
            field=models.CharField(default="2.4", max_length=24),
        ),
        migrations.AddField(
            model_name="garmentdesignversion",
            name="product_class",
            field=models.CharField(choices=[("apparel", "Apparel"), ("accessory", "Accessory"), ("headwear", "Headwear")], default="apparel", max_length=24),
        ),
        migrations.AddField(
            model_name="garmentdesignversion",
            name="size_system",
            field=models.CharField(choices=[("multi_size", "Multi size"), ("one_size", "One size"), ("one_size_accessory", "One size accessory")], default="multi_size", max_length=32),
        ),
        migrations.AddField(
            model_name="garmentdesignversion",
            name="decoration_applicability",
            field=models.CharField(choices=[("undeclared", "Undeclared"), ("configured", "Decoration configured"), ("not_applicable", "Decoration not applicable")], default="undeclared", max_length=24),
        ),
        migrations.AddField(model_name="garmentdesignversion", name="requires_3d_source", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="garmentdesignversion", name="technical_policy", field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name="garmentdesignversion", name="qc_requirements", field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name="garmentdesignversion", name="production_engineering_validated", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="garmentdesignversion", name="production_engineering_notes", field=models.TextField(blank=True)),
        migrations.AddField(model_name="designasset", name="symbolic_ref", field=models.CharField(blank=True, max_length=120, null=True, unique=True)),
        migrations.AddField(model_name="designasset", name="technical_role", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="designasset", name="size_label", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="designasset", name="reference_only", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="decorationzone", name="symbolic_ref", field=models.CharField(blank=True, max_length=120, null=True, unique=True)),
        migrations.AddField(model_name="decorationzone", name="surface", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="decorationzone", name="allowed_methods", field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name="decorationzone", name="minimum_dpi", field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="decorationzone", name="embroidery_constraints", field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name="decorationzone", name="reference_only", field=models.BooleanField(default=False)),
        migrations.AlterField(
            model_name="decorationzone",
            name="method",
            field=models.CharField(choices=[("print", "Print (legacy)"), ("embroidery", "Embroidery"), ("both", "Print or embroidery (legacy)")], default="both", max_length=20),
        ),
        migrations.CreateModel(
            name="DesignPointOfMeasure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbolic_ref", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=180)),
                ("unit", models.CharField(choices=[("mm", "Millimetres"), ("cm", "Centimetres"), ("in", "Inches")], default="cm", max_length=8)),
                ("tolerance_plus", models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ("tolerance_minus", models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ("required", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="points_of_measure", to="design.garmentdesignversion")),
            ],
            options={"ordering": ("sort_order", "id")},
        ),
        migrations.AddConstraint(model_name="designpointofmeasure", constraint=models.UniqueConstraint(fields=("version", "symbolic_ref"), name="unique_version_pom_ref")),
        migrations.CreateModel(
            name="DesignPOMValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.DecimalField(decimal_places=3, max_digits=10)),
                ("point", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="values", to="design.designpointofmeasure")),
                ("size", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pom_values", to="design.sizechartrow")),
            ],
        ),
        migrations.AddConstraint(model_name="designpomvalue", constraint=models.UniqueConstraint(fields=("point", "size"), name="unique_pom_size_value")),
        migrations.CreateModel(
            name="DesignMaterial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbolic_ref", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=220)),
                ("composition", models.CharField(blank=True, max_length=255)),
                ("gsm", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="materials", to="design.garmentdesignversion")),
            ],
            options={"ordering": ("sort_order", "id")},
        ),
        migrations.AddConstraint(model_name="designmaterial", constraint=models.UniqueConstraint(fields=("version", "symbolic_ref"), name="unique_version_material_ref")),
        migrations.CreateModel(
            name="DesignPatternRequirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("required", models.BooleanField(default=True)),
                ("declared_scale_1_to_1", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("pattern_asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="pattern_requirements", to="design.designasset")),
                ("size", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="pattern_requirement", to="design.sizechartrow")),
                ("version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pattern_requirements", to="design.garmentdesignversion")),
            ],
        ),
        migrations.CreateModel(
            name="DesignColorway",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbolic_ref", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=160)),
                ("hex_color", models.CharField(blank=True, max_length=16)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="colorways", to="design.garmentdesignversion")),
            ],
            options={"ordering": ("sort_order", "id")},
        ),
        migrations.AddConstraint(model_name="designcolorway", constraint=models.UniqueConstraint(fields=("version", "symbolic_ref"), name="unique_version_colorway_ref")),
        migrations.CreateModel(
            name="DesignColorwayImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("thumbnail", "Thumbnail"), ("product_card_4_3", "Product card 4:3"), ("product_detail", "Product detail"), ("zoom_reference", "Zoom reference"), ("technical_reference", "Technical reference")], max_length=32)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="colorway_roles", to="design.designasset")),
                ("colorway", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="design.designcolorway")),
            ],
            options={"ordering": ("sort_order", "id")},
        ),
        migrations.AddConstraint(model_name="designcolorwayimage", constraint=models.UniqueConstraint(fields=("colorway", "role", "asset"), name="unique_colorway_role_asset")),
        migrations.CreateModel(
            name="TechnicalBlocker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("status", models.CharField(choices=[("open", "Open"), ("resolved", "Resolved")], db_index=True, default="open", max_length=16)),
                ("reference_only", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_design_blockers", to=settings.AUTH_USER_MODEL)),
                ("version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="technical_blockers", to="design.garmentdesignversion")),
            ],
        ),
        migrations.AddConstraint(model_name="technicalblocker", constraint=models.UniqueConstraint(fields=("version", "code"), name="unique_version_blocker_code")),
        migrations.CreateModel(
            name="ReferenceDataset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dataset_name", models.CharField(max_length=180)),
                ("dataset_version", models.CharField(max_length=40)),
                ("machine_contract_identity", models.CharField(max_length=180)),
                ("machine_contract_version", models.CharField(max_length=40)),
                ("machine_contract_sha256", models.CharField(max_length=64)),
                ("image_role_contract_identity", models.CharField(max_length=180)),
                ("image_role_contract_version", models.CharField(max_length=40)),
                ("image_role_contract_sha256", models.CharField(max_length=64)),
                ("reference_notice", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(model_name="referencedataset", constraint=models.UniqueConstraint(fields=("dataset_name", "dataset_version"), name="unique_reference_dataset_version")),
        migrations.CreateModel(
            name="ReferencePackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_ref", models.CharField(max_length=32)),
                ("product_name", models.CharField(max_length=180)),
                ("canonical_filename", models.CharField(max_length=255)),
                ("package_sha256", models.CharField(max_length=64)),
                ("source_design_ref", models.CharField(max_length=100)),
                ("source_gdv_ref", models.CharField(max_length=100)),
                ("status", models.CharField(choices=[("approved_reference", "Approved reference")], default="approved_reference", max_length=32)),
                ("golden_reference_complete", models.BooleanField(default=True)),
                ("public_reference_allowed", models.BooleanField(default=True)),
                ("production_engineering_validated", models.BooleanField(default=False)),
                ("synthetic_reference", models.BooleanField(default=True)),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="packages", to="design.referencedataset")),
            ],
        ),
        migrations.AddConstraint(model_name="referencepackage", constraint=models.UniqueConstraint(fields=("dataset", "product_ref"), name="unique_reference_product_ref")),
        migrations.AddConstraint(model_name="referencepackage", constraint=models.UniqueConstraint(fields=("dataset", "canonical_filename"), name="unique_reference_filename")),
        migrations.CreateModel(
            name="DesignReferenceProvenance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_symbolic_ids", models.JSONField(blank=True, default=dict)),
                ("import_implementation_version", models.CharField(max_length=40)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("design", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="reference_provenance", to="design.garmentdesign")),
                ("imported_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reference_imports", to=settings.AUTH_USER_MODEL)),
                ("package", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="design_provenance", to="design.referencepackage")),
                ("version", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="reference_provenance", to="design.garmentdesignversion")),
            ],
        ),
    ]
