from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[("checkout","0001_initial"),("organizations","0002_align_index_names"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="FinancePolicy",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(default="default",max_length=80,unique=True)),("platform_fee_bps",models.PositiveIntegerField(default=1000,help_text="Platform fee in basis points; 1000 = 10%.")),("settlement_delay_days",models.PositiveIntegerField(default=7)),("minimum_payout",models.DecimalField(decimal_places=2,default="100.00",max_digits=12)),("is_active",models.BooleanField(db_index=True,default=True)),("updated_at",models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name="FinanceAccount",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("account_type",models.CharField(choices=[("organization","Organization"),("platform","Platform")],max_length=20)),("currency",models.CharField(default="EGP",max_length=3)),("created_at",models.DateTimeField(auto_now_add=True)),("organization",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="finance_accounts",to="organizations.organization"))],options={"constraints":[models.UniqueConstraint(fields=("organization","currency"),name="unique_org_finance_currency")],"indexes":[models.Index(fields=["account_type","currency"],name="finance_acct_type_idx")]}),
        migrations.CreateModel(name="PayoutProfile",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("method",models.CharField(choices=[("bank","Bank transfer"),("manual","Manual settlement")],default="bank",max_length=20)),("account_holder",models.CharField(max_length=180)),("destination_hint",models.CharField(help_text="Masked/non-sensitive payout destination only.",max_length=120)),("status",models.CharField(choices=[("draft","Draft"),("pending","Pending verification"),("verified","Verified"),("rejected","Rejected")],db_index=True,default="draft",max_length=20)),("verification_notes",models.TextField(blank=True)),("verified_at",models.DateTimeField(blank=True,null=True)),("updated_at",models.DateTimeField(auto_now=True)),("organization",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="finance_payout_profile",to="organizations.organization")),("verified_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="verified_payout_profiles",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="OrderFinance",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("recognized","Recognized"),("reversed","Reversed")],db_index=True,default="recognized",max_length=20)),("gross_amount",models.DecimalField(decimal_places=2,max_digits=12)),("platform_fee",models.DecimalField(decimal_places=2,max_digits=12)),("manufacturer_payable",models.DecimalField(decimal_places=2,default=0,max_digits=12)),("designer_earnings",models.DecimalField(decimal_places=2,max_digits=12)),("currency",models.CharField(max_length=3)),("policy_snapshot",models.JSONField(default=dict)),("recognized_at",models.DateTimeField()),("available_at",models.DateTimeField(db_index=True)),("designer_account",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="designer_order_finance",to="finance.financeaccount")),("manufacturer_account",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="manufacturer_order_finance",to="finance.financeaccount")),("order",models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name="finance_record",to="checkout.customerorder"))],options={"ordering":("-recognized_at",)}),
        migrations.CreateModel(name="SettlementRequest",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("amount",models.DecimalField(decimal_places=2,max_digits=12)),("currency",models.CharField(max_length=3)),("status",models.CharField(choices=[("requested","Requested"),("approved","Approved"),("paid","Paid"),("rejected","Rejected"),("cancelled","Cancelled")],db_index=True,default="requested",max_length=20)),("payout_snapshot",models.JSONField(default=dict)),("review_notes",models.TextField(blank=True)),("external_reference",models.CharField(blank=True,max_length=180)),("requested_at",models.DateTimeField(auto_now_add=True)),("reviewed_at",models.DateTimeField(blank=True,null=True)),("paid_at",models.DateTimeField(blank=True,null=True)),("account",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="settlement_requests",to="finance.financeaccount")),("organization",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="settlement_requests",to="organizations.organization")),("paid_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="paid_settlements",to=settings.AUTH_USER_MODEL)),("payout_profile",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="settlement_requests",to="finance.payoutprofile")),("requested_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="requested_settlements",to=settings.AUTH_USER_MODEL)),("reviewed_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="reviewed_settlements",to=settings.AUTH_USER_MODEL))],options={"ordering":("-requested_at",),"indexes":[models.Index(fields=["organization","status"],name="settle_org_status_idx")]}),
        migrations.CreateModel(name="LedgerEntry",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("entry_type",models.CharField(choices=[("designer_earning","Designer earning"),("manufacturer_earning","Manufacturer earning"),("platform_fee","Platform fee"),("settlement","Settlement"),("adjustment","Adjustment"),("reversal","Reversal")],max_length=32)),("amount",models.DecimalField(decimal_places=2,help_text="Signed amount; credits positive, debits negative.",max_digits=12)),("currency",models.CharField(max_length=3)),("available_at",models.DateTimeField(db_index=True)),("memo",models.CharField(blank=True,max_length=255)),("created_at",models.DateTimeField(auto_now_add=True)),("account",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="ledger_entries",to="finance.financeaccount")),("created_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="finance_ledger_entries",to=settings.AUTH_USER_MODEL)),("order_finance",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="ledger_entries",to="finance.orderfinance")),("settlement",models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="ledger_entry",to="finance.settlementrequest"))],options={"ordering":("created_at","id"),"indexes":[models.Index(fields=["account","available_at"],name="ledger_acct_avail_idx")]}),
        migrations.CreateModel(name="FinanceAdjustment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("amount",models.DecimalField(decimal_places=2,max_digits=12)),("reason",models.CharField(max_length=255)),("created_at",models.DateTimeField(auto_now_add=True)),("account",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="adjustments",to="finance.financeaccount")),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="finance_adjustments",to=settings.AUTH_USER_MODEL)),("order_finance",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="adjustments",to="finance.orderfinance"))],options={"ordering":("-created_at",)}),
    ]
