from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),("organizations","0002_align_index_names"),("media","0002_rename_media_asset_index"),("artwork","0001_initial")]
    operations=[
        migrations.CreateModel(name="ManufacturerListing",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("draft","Draft"),("published","Published"),("paused","Paused")],db_index=True,default="draft",max_length=20)),("headline_en",models.CharField(blank=True,max_length=220)),("headline_ar",models.CharField(blank=True,max_length=220)),("overview_en",models.TextField(blank=True)),("overview_ar",models.TextField(blank=True)),("public_email",models.EmailField(blank=True,max_length=254)),("public_phone",models.CharField(blank=True,max_length=50)),("accepts_rfq",models.BooleanField(default=True)),("sample_orders",models.BooleanField(default=False)),("min_order_quantity",models.PositiveIntegerField(blank=True,null=True)),("lead_time_min_days",models.PositiveIntegerField(blank=True,null=True)),("lead_time_max_days",models.PositiveIntegerField(blank=True,null=True)),("available_monthly_capacity",models.PositiveIntegerField(blank=True,null=True)),("materials",models.JSONField(blank=True,default=list)),("production_methods",models.JSONField(blank=True,default=list)),("markets",models.JSONField(blank=True,default=list)),("certifications",models.JSONField(blank=True,default=list)),("last_capacity_update",models.DateTimeField(blank=True,null=True)),("published_at",models.DateTimeField(blank=True,null=True)),("updated_at",models.DateTimeField(auto_now=True)),("organization",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="marketplace_listing",to="organizations.organization"))],options={"ordering":("organization__display_name",),"indexes":[models.Index(fields=["status","accepts_rfq"],name="mkt_listing_status_idx")]}),
        migrations.CreateModel(name="ManufacturerCapability",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("capability_type",models.CharField(choices=[("cut_sew","Cut & sew"),("print","Printing"),("embroidery","Embroidery"),("sampling","Sampling"),("pattern","Pattern making"),("finishing","Finishing"),("packaging","Packaging"),("other","Other")],max_length=24)),("name",models.CharField(max_length=160)),("description",models.TextField(blank=True)),("methods",models.JSONField(blank=True,default=list)),("min_quantity",models.PositiveIntegerField(blank=True,null=True)),("max_quantity",models.PositiveIntegerField(blank=True,null=True)),("lead_time_days",models.PositiveIntegerField(blank=True,null=True)),("is_active",models.BooleanField(default=True)),("listing",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="capabilities",to="manufacturer_marketplace.manufacturerlisting"))],options={"ordering":("capability_type","name")}),
        migrations.AddConstraint(model_name="manufacturercapability",constraint=models.UniqueConstraint(fields=("listing","capability_type","name"),name="unique_listing_capability")),
        migrations.CreateModel(name="ManufacturerPortfolioAsset",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("caption",models.CharField(blank=True,max_length=220)),("sort_order",models.PositiveIntegerField(default=0)),("created_at",models.DateTimeField(auto_now_add=True)),("listing",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="portfolio_assets",to="manufacturer_marketplace.manufacturerlisting")),("media_asset",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="manufacturer_portfolio_assets",to="media.mediaasset"))],options={"ordering":("sort_order","id")}),
        migrations.CreateModel(name="RFQ",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=220)),("quantity",models.PositiveIntegerField()),("size_breakdown",models.JSONField(blank=True,default=dict)),("color_requirements",models.JSONField(blank=True,default=list)),("requested_methods",models.JSONField(blank=True,default=list)),("target_unit_price",models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),("currency",models.CharField(default="EGP",max_length=3)),("desired_delivery_date",models.DateField(blank=True,null=True)),("delivery_country",models.CharField(default="EG",max_length=2)),("delivery_city",models.CharField(blank=True,max_length=120)),("notes",models.TextField(blank=True)),("status",models.CharField(choices=[("draft","Draft"),("open","Open"),("quoted","Quotes received"),("selected","Manufacturer selected"),("closed","Closed"),("cancelled","Cancelled")],db_index=True,default="draft",max_length=20)),("created_at",models.DateTimeField(auto_now_add=True)),("opened_at",models.DateTimeField(blank=True,null=True)),("selected_at",models.DateTimeField(blank=True,null=True)),("closed_at",models.DateTimeField(blank=True,null=True)),("updated_at",models.DateTimeField(auto_now=True)),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="created_manufacturer_rfqs",to=settings.AUTH_USER_MODEL)),("designed_product",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="manufacturer_rfqs",to="artwork.designedproduct")),("designer_organization",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="manufacturer_rfqs",to="organizations.organization"))],options={"ordering":("-updated_at",),"indexes":[models.Index(fields=["designer_organization","status"],name="rfq_designer_status_idx")]}),
        migrations.CreateModel(name="RFQInvitation",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("invited","Invited"),("viewed","Viewed"),("declined","Declined"),("quoted","Quoted")],db_index=True,default="invited",max_length=20)),("sent_at",models.DateTimeField(auto_now_add=True)),("viewed_at",models.DateTimeField(blank=True,null=True)),("responded_at",models.DateTimeField(blank=True,null=True)),("manufacturer",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="rfq_invitations",to="organizations.organization")),("rfq",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="invitations",to="manufacturer_marketplace.rfq"))],options={"ordering":("-sent_at",)}),
        migrations.AddConstraint(model_name="rfqinvitation",constraint=models.UniqueConstraint(fields=("rfq","manufacturer"),name="unique_rfq_manufacturer_invite")),
        migrations.CreateModel(name="ManufacturerQuote",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("draft","Draft"),("submitted","Submitted"),("withdrawn","Withdrawn"),("accepted","Accepted"),("declined","Declined"),("expired","Expired")],db_index=True,default="draft",max_length=20)),("unit_price",models.DecimalField(decimal_places=2,max_digits=12)),("setup_fee",models.DecimalField(decimal_places=2,default=0,max_digits=12)),("sample_fee",models.DecimalField(decimal_places=2,default=0,max_digits=12)),("shipping_estimate",models.DecimalField(decimal_places=2,default=0,max_digits=12)),("currency",models.CharField(default="EGP",max_length=3)),("minimum_order_quantity",models.PositiveIntegerField(default=1)),("production_lead_days",models.PositiveIntegerField()),("sample_lead_days",models.PositiveIntegerField(blank=True,null=True)),("valid_until",models.DateField(blank=True,null=True)),("notes",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("submitted_at",models.DateTimeField(blank=True,null=True)),("updated_at",models.DateTimeField(auto_now=True)),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="manufacturer_quotes",to=settings.AUTH_USER_MODEL)),("invitation",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="quote",to="manufacturer_marketplace.rfqinvitation"))],options={"ordering":("-updated_at",)}),
        migrations.CreateModel(name="ManufacturerSelection",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("selected_at",models.DateTimeField(auto_now_add=True)),("manufacturer",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="marketplace_selections",to="organizations.organization")),("quote",models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name="selection",to="manufacturer_marketplace.manufacturerquote")),("rfq",models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name="selection",to="manufacturer_marketplace.rfq")),("selected_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="manufacturer_selections",to=settings.AUTH_USER_MODEL))]),
    ]
