# Generated for FABINZI V2-3 — Subscriptions + Entitlements + Team
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0004_v2_application_review_target_and_public_revision_states"),
        ("design", "0001_initial"),
        ("artwork", "0001_initial"),
        ("manufacturer_marketplace", "0001_initial"),
        ("storefront", "0002_visual_studio_elements"),
        ("notifications", "0002_preferences_and_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlanPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                ("public_name_ar", models.CharField(max_length=180)),
                ("public_name_en", models.CharField(max_length=180)),
                ("audience", models.CharField(choices=[("designer", "Designer"), ("manufacturer", "Manufacturer")], db_index=True, max_length=20)),
                ("monthly_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("tax_inclusive", models.BooleanField(default=True)),
                ("trial_months", models.PositiveSmallIntegerField(default=0)),
                ("designer_active_design_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("designer_active_artwork_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("manufacturer_monthly_offer_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("team_subaccount_limit", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("effective_from", models.DateField(db_index=True)),
                ("effective_to", models.DateField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_subscription_plan_policies", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("code", "-effective_from", "-version")},
        ),
        migrations.AddConstraint(model_name="subscriptionplanpolicy", constraint=models.UniqueConstraint(fields=("code", "version"), name="unique_subscription_plan_version")),
        migrations.AddConstraint(model_name="subscriptionplanpolicy", constraint=models.UniqueConstraint(fields=("code", "effective_from"), name="unique_subscription_plan_effective_date")),
        migrations.CreateModel(
            name="OrganizationSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("trialing", "Trialing"), ("active", "Active"), ("past_due", "Past due"), ("grace_period", "Grace period"), ("cancelled", "Cancelled"), ("expired", "Expired"), ("downgraded", "Downgraded")], db_index=True, max_length=24)),
                ("started_at", models.DateTimeField()),
                ("trial_started_at", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("trial_consumed", models.BooleanField(default=False)),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("next_billing_at", models.DateTimeField(blank=True, null=True)),
                ("grace_started_on", models.DateField(blank=True, null=True)),
                ("grace_ends_on", models.DateField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("downgraded_at", models.DateTimeField(blank=True, null=True)),
                ("policy_snapshot", models.JSONField(default=dict)),
                ("price_snapshot", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="current_subscriptions", to="subscriptions.subscriptionplanpolicy")),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="professional_subscription", to="organizations.organization")),
            ],
            options={"permissions": [("manage_professional_subscription", "Can manage professional subscription lifecycle")]},
        ),
        migrations.AddIndex(model_name="organizationsubscription", index=models.Index(fields=["status", "current_period_end"], name="prosub_status_period_idx")),
        migrations.CreateModel(
            name="SubscriptionPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                ("plan_code", models.CharField(max_length=64)),
                ("status_snapshot", models.CharField(max_length=24)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("policy_snapshot", models.JSONField(default=dict)),
                ("price_snapshot", models.JSONField(default=dict)),
                ("billing_reference", models.CharField(blank=True, max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="periods", to="subscriptions.organizationsubscription")),
            ],
            options={"ordering": ("-sequence",)},
        ),
        migrations.AddConstraint(model_name="subscriptionperiod", constraint=models.UniqueConstraint(fields=("subscription", "sequence"), name="unique_subscription_period_sequence")),
        migrations.CreateModel(
            name="SubscriptionBillingConfirmation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plan_code", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("provider", models.CharField(max_length=40)),
                ("provider_reference", models.CharField(max_length=180)),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("status", models.CharField(choices=[("confirmed", "Confirmed"), ("revoked", "Revoked")], default="confirmed", max_length=16)),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="confirmed_professional_subscription_billing", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_billing_confirmations", to="organizations.organization")),
            ],
            options={"ordering": ("-confirmed_at",)},
        ),
        migrations.AddConstraint(model_name="subscriptionbillingconfirmation", constraint=models.UniqueConstraint(fields=("provider", "provider_reference"), name="unique_subscription_provider_reference")),
        migrations.CreateModel(
            name="ManufacturerOfferUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plan_code", models.CharField(max_length=64)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("consumed_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="manufacturer_offer_usage", to="organizations.organization")),
                ("quote", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_usage", to="manufacturer_marketplace.manufacturerquote")),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="manufacturer_offer_usage", to="subscriptions.organizationsubscription")),
            ],
            options={"ordering": ("-consumed_at",)},
        ),
        migrations.AddIndex(model_name="manufacturerofferusage", index=models.Index(fields=["organization", "period_start"], name="mfr_usage_org_period_idx")),
        migrations.CreateModel(
            name="TeamInvitationConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("invitation_expiry_days", models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="team_invitation_configuration_updates", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="TeamInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(choices=[("owner", "Owner"), ("manager", "Manager"), ("designer", "Designer"), ("design_manager", "Design Manager"), ("accountant", "Accountant"), ("production_manager", "Production Manager"), ("operator", "Operator"), ("qc", "QC")], max_length=32)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("declined", "Declined"), ("expired", "Expired"), ("revoked", "Revoked")], db_index=True, default="pending", max_length=16)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="accepted_team_invitations", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_team_invitations", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="team_invitations", to="organizations.organization")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(model_name="teaminvitation", constraint=models.UniqueConstraint(condition=models.Q(("status", "pending")), fields=("organization", "email"), name="unique_pending_team_invitation_email")),
        migrations.CreateModel(
            name="MembershipPlanSuspension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("suspended_by_plan", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, max_length=180)),
                ("suspended_at", models.DateTimeField()),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("membership", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="plan_suspension", to="organizations.membership")),
            ],
        ),
        migrations.CreateModel(
            name="DesignPlanEntitlementState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plan_paused", models.BooleanField(db_index=True, default=False)),
                ("retained", models.BooleanField(default=False)),
                ("protected_active_chain", models.BooleanField(default=False)),
                ("pause_reason", models.CharField(blank=True, max_length=180)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("design", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="plan_entitlement_state", to="design.garmentdesign")),
            ],
        ),
        migrations.CreateModel(
            name="ArtworkPlanEntitlementState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plan_paused", models.BooleanField(db_index=True, default=False)),
                ("retained", models.BooleanField(default=False)),
                ("protected_active_chain", models.BooleanField(default=False)),
                ("pause_reason", models.CharField(blank=True, max_length=180)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("artwork", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="plan_entitlement_state", to="artwork.artwork")),
            ],
        ),
        migrations.CreateModel(
            name="StoreProductPlanPause",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("previous_status", models.CharField(max_length=20)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("paused_at", models.DateTimeField()),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("store_product", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_plan_pause", to="storefront.storeproduct")),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionReminderMilestone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, unique=True)),
                ("label_en", models.CharField(max_length=180)),
                ("label_ar", models.CharField(max_length=180)),
                ("offset_days", models.SmallIntegerField()),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("offset_days", "code")},
        ),
        migrations.CreateModel(
            name="SubscriptionReminderEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("due_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("milestone", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="subscriptions.subscriptionremindermilestone")),
                ("notification", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="subscription_reminder_events", to="notifications.notification")),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reminder_events", to="subscriptions.organizationsubscription")),
            ],
        ),
        migrations.AddConstraint(model_name="subscriptionreminderevent", constraint=models.UniqueConstraint(fields=("subscription", "due_date", "milestone"), name="unique_subscription_reminder_event")),
        migrations.CreateModel(
            name="SubscriptionTrialException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField()),
                ("old_trial_state", models.JSONField(default=dict)),
                ("new_trial_state", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_trial_exceptions", to=settings.AUTH_USER_MODEL)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="trial_exceptions", to="subscriptions.organizationsubscription")),
            ],
            options={"ordering": ("-created_at",)},
        ),
    ]
