from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial=True
    dependencies=[("checkout","0001_initial"),("manufacturer_marketplace","0001_initial"),("media","0002_rename_media_asset_index"),("organizations","0002_align_index_names"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="FulfillmentRecord",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("waiting_production","Waiting for production"),("ready_to_pack","Ready to pack"),("packed","Packed"),("shipped","Shipped"),("delivered","Delivered"),("failed","Delivery failed"),("returned","Returned"),("cancelled","Cancelled")],db_index=True,max_length=28)),("carrier",models.CharField(blank=True,max_length=120)),("tracking_number",models.CharField(blank=True,max_length=180)),("tracking_url",models.URLField(blank=True)),("packed_at",models.DateTimeField(blank=True,null=True)),("shipped_at",models.DateTimeField(blank=True,null=True)),("delivered_at",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("order",models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name="fulfillment",to="checkout.customerorder"))],options={"ordering":("-updated_at",),"indexes":[models.Index(fields=["status","updated_at"],name="fulfill_status_time_idx")]}),
        migrations.CreateModel(name="ProductionJob",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("awaiting_assignment","Awaiting manufacturer"),("queued","Queued"),("in_production","In production"),("qc_pending","QC pending"),("qc_failed","QC failed"),("ready_for_fulfillment","Ready for fulfillment"),("cancelled","Cancelled")],db_index=True,default="awaiting_assignment",max_length=32)),("production_notes",models.TextField(blank=True)),("target_completion_date",models.DateField(blank=True,null=True)),("assigned_at",models.DateTimeField(blank=True,null=True)),("started_at",models.DateTimeField(blank=True,null=True)),("ready_at",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("manufacturer",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="production_jobs",to="organizations.organization")),("order",models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name="production_job",to="checkout.customerorder")),("selection",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="production_jobs",to="manufacturer_marketplace.manufacturerselection"))],options={"ordering":("-updated_at",),"indexes":[models.Index(fields=["manufacturer","status"],name="prodjob_mfr_status_idx")]}),
        migrations.CreateModel(name="FulfillmentEvent",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("waiting_production","Waiting for production"),("ready_to_pack","Ready to pack"),("packed","Packed"),("shipped","Shipped"),("delivered","Delivered"),("failed","Delivery failed"),("returned","Returned"),("cancelled","Cancelled")],max_length=28)),("note",models.CharField(blank=True,max_length=255)),("created_at",models.DateTimeField(auto_now_add=True)),("actor",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="fulfillment_events",to=settings.AUTH_USER_MODEL)),("fulfillment",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="events",to="operations.fulfillmentrecord"))],options={"ordering":("created_at",)}),
        migrations.CreateModel(name="ProductionAsset",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("kind",models.CharField(choices=[("work_instruction","Work instruction"),("qc_evidence","QC evidence"),("other","Other")],max_length=24)),("label",models.CharField(blank=True,max_length=180)),("created_at",models.DateTimeField(auto_now_add=True)),("job",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="assets",to="operations.productionjob")),("media_asset",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="production_assets",to="media.mediaasset")),("uploaded_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="production_assets",to=settings.AUTH_USER_MODEL))],options={"ordering":("created_at",)}),
        migrations.CreateModel(name="ProductionMilestone",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("kind",models.CharField(choices=[("materials","Materials"),("cutting","Cutting"),("assembly","Assembly / Sewing"),("decoration","Printing / Embroidery"),("finishing","Finishing")],max_length=24)),("status",models.CharField(choices=[("pending","Pending"),("in_progress","In progress"),("completed","Completed"),("blocked","Blocked")],db_index=True,default="pending",max_length=20)),("notes",models.TextField(blank=True)),("started_at",models.DateTimeField(blank=True,null=True)),("completed_at",models.DateTimeField(blank=True,null=True)),("updated_at",models.DateTimeField(auto_now=True)),("job",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="milestones",to="operations.productionjob")),("updated_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="updated_production_milestones",to=settings.AUTH_USER_MODEL))],options={"ordering":("id",),"constraints":[models.UniqueConstraint(fields=("job","kind"),name="unique_job_milestone_kind")]}),
        migrations.CreateModel(name="QCInspection",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("decision",models.CharField(choices=[("passed","Passed"),("failed","Failed"),("rework","Rework required")],max_length=16)),("checklist",models.JSONField(default=dict)),("notes",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("inspected_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="qc_inspections",to=settings.AUTH_USER_MODEL)),("job",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="qc_inspections",to="operations.productionjob"))],options={"ordering":("-created_at",)}),
    ]
