from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),("organizations","0002_align_index_names"),("media","0002_rename_media_asset_index"),("design","0001_initial"),("artwork","0001_initial")]
    operations=[
        migrations.CreateModel(name="Storefront",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("slug",models.SlugField(max_length=100,unique=True)),("status",models.CharField(choices=[("draft","Draft"),("published","Published"),("paused","Paused")],db_index=True,default="draft",max_length=20)),("name_en",models.CharField(max_length=180)),("name_ar",models.CharField(blank=True,max_length=180)),("about_en",models.TextField(blank=True)),("about_ar",models.TextField(blank=True)),("published_at",models.DateTimeField(blank=True,null=True)),("updated_at",models.DateTimeField(auto_now=True)),("logo",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="storefront_logos",to="media.mediaasset")),("organization",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="storefront",to="organizations.organization"))],options={"ordering":("name_en",)}),
        migrations.CreateModel(name="StoreProduct",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("slug",models.SlugField(max_length=120)),("status",models.CharField(choices=[("draft","Draft"),("published","Published"),("hidden","Hidden"),("archived","Archived")],db_index=True,default="draft",max_length=20)),("title_en",models.CharField(max_length=220)),("title_ar",models.CharField(blank=True,max_length=220)),("description_en",models.TextField(blank=True)),("description_ar",models.TextField(blank=True)),("base_price",models.DecimalField(decimal_places=2,max_digits=12)),("currency",models.CharField(default="EGP",max_length=3)),("fulfillment_mode",models.CharField(choices=[("made_to_order","Made to order"),("stock","Stock")],default="made_to_order",max_length=20)),("lead_time_days",models.PositiveIntegerField(blank=True,null=True)),("customization_enabled",models.BooleanField(default=False)),("featured",models.BooleanField(default=False)),("published_at",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("designed_product",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="store_products",to="artwork.designedproduct")),("storefront",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="products",to="storefront.storefront"))],options={"ordering":("-featured","-updated_at"),"indexes":[models.Index(fields=["storefront","status"],name="store_product_status_idx")]}),
        migrations.AddConstraint(model_name="storeproduct",constraint=models.UniqueConstraint(fields=("storefront","slug"),name="unique_store_product_slug")),
        migrations.CreateModel(name="ProductVariant",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("sku",models.CharField(max_length=120,unique=True)),("size",models.CharField(blank=True,max_length=40)),("color_name",models.CharField(blank=True,max_length=80)),("color_hex",models.CharField(blank=True,max_length=7)),("price_adjustment",models.DecimalField(decimal_places=2,default=0,max_digits=12)),("stock_quantity",models.PositiveIntegerField(blank=True,null=True)),("is_active",models.BooleanField(default=True)),("product",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="variants",to="storefront.storeproduct"))],options={"ordering":("size","color_name","sku")}),
        migrations.CreateModel(name="StoreProductImage",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("alt_en",models.CharField(blank=True,max_length=180)),("alt_ar",models.CharField(blank=True,max_length=180)),("sort_order",models.PositiveIntegerField(default=0)),("media_asset",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="store_product_images",to="media.mediaasset")),("product",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="images",to="storefront.storeproduct"))],options={"ordering":("sort_order","id")}),
        migrations.CreateModel(name="StudioProject",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("draft","Draft"),("ready","Ready for checkout"),("archived","Archived")],db_index=True,default="draft",max_length=20)),("quantity",models.PositiveIntegerField(default=1)),("customer_notes",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("ready_at",models.DateTimeField(blank=True,null=True)),("customer",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="studio_projects",to=settings.AUTH_USER_MODEL)),("preview",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="studio_previews",to="media.mediaasset")),("product",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="studio_projects",to="storefront.storeproduct")),("variant",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="studio_projects",to="storefront.productvariant"))],options={"ordering":("-updated_at",)}),
        migrations.CreateModel(name="CustomerCustomization",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("enabled",models.BooleanField(default=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("project",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="customization",to="storefront.studioproject"))]),
        migrations.CreateModel(name="CustomizationElement",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("kind",models.CharField(choices=[("text","Text"),("image","Customer image")],max_length=16)),("text",models.CharField(blank=True,max_length=240)),("transform",models.JSONField(default=dict)),("style",models.JSONField(blank=True,default=dict)),("sort_order",models.PositiveIntegerField(default=0)),("customization",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="elements",to="storefront.customercustomization")),("decoration_zone",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="customer_customization_elements",to="design.decorationzone")),("media_asset",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="customization_elements",to="media.mediaasset"))],options={"ordering":("sort_order","id")}),
    ]
