from django.urls import path

from .customer import (
    CustomerArtworkDetailAPIView,
    CustomerArtworkListAPIView,
    CustomerBootstrapAPIView,
    CustomerCartAPIView,
    CustomerCartCheckoutAPIView,
    CustomerCartItemCreateAPIView,
    CustomerCartItemDetailAPIView,
    CustomerCheckoutDetailAPIView,
    CustomerLoginAPIView,
    CustomerLogoutAPIView,
    CustomerMeAPIView,
    CustomerNotificationListAPIView,
    CustomerNotificationPreferenceAPIView,
    CustomerNotificationReadAllAPIView,
    CustomerNotificationReadAPIView,
    CustomerPaymentOptionsAPIView,
    CustomerPlaceCheckoutAPIView,
    CustomerPrivateMediaAPIView,
    CustomerProductDetailAPIView,
    CustomerProductListAPIView,
    CustomerPurchaseDetailAPIView,
    CustomerPurchaseListAPIView,
    CustomerRefreshAPIView,
    CustomerStoreDetailAPIView,
    CustomerStoreListAPIView,
    CustomerStudioCheckoutAPIView,
    CustomerStudioCustomizationAPIView,
    CustomerStudioElementAPIView,
    CustomerStudioElementDetailAPIView,
    CustomerStudioProjectDetailAPIView,
    CustomerStudioProjectsAPIView,
    CustomerStudioReadyAPIView,
    CustomerStudioValidationAPIView,
)
from .customer_upload import FrozenCustomerStudioUploadAPIView

app_name = "customer"

urlpatterns = [
    path("bootstrap/", CustomerBootstrapAPIView.as_view(), name="bootstrap"),
    path("auth/login/", CustomerLoginAPIView.as_view(), name="login"),
    path("auth/refresh/", CustomerRefreshAPIView.as_view(), name="refresh"),
    path("auth/logout/", CustomerLogoutAPIView.as_view(), name="logout"),
    path("me/", CustomerMeAPIView.as_view(), name="me"),
    path("stores/", CustomerStoreListAPIView.as_view(), name="stores"),
    path("stores/<slug:store_slug>/", CustomerStoreDetailAPIView.as_view(), name="store-detail"),
    path("products/", CustomerProductListAPIView.as_view(), name="products"),
    path("stores/<slug:store_slug>/products/<slug:product_slug>/", CustomerProductDetailAPIView.as_view(), name="product-detail"),
    path("artworks/", CustomerArtworkListAPIView.as_view(), name="artworks"),
    path("artworks/<int:artwork_id>/", CustomerArtworkDetailAPIView.as_view(), name="artwork-detail"),
    path("studio-projects/", CustomerStudioProjectsAPIView.as_view(), name="studio-projects"),
    path("studio-projects/<int:project_id>/", CustomerStudioProjectDetailAPIView.as_view(), name="studio-project-detail"),
    path("studio-projects/<int:project_id>/customization/", CustomerStudioCustomizationAPIView.as_view(), name="studio-customization"),
    path("studio-projects/<int:project_id>/uploads/", FrozenCustomerStudioUploadAPIView.as_view(), name="studio-upload"),
    path("studio-projects/<int:project_id>/elements/", CustomerStudioElementAPIView.as_view(), name="studio-element"),
    path("studio-projects/<int:project_id>/elements/<int:element_id>/", CustomerStudioElementDetailAPIView.as_view(), name="studio-element-detail"),
    path("studio-projects/<int:project_id>/validation/", CustomerStudioValidationAPIView.as_view(), name="studio-validation"),
    path("studio-projects/<int:project_id>/ready/", CustomerStudioReadyAPIView.as_view(), name="studio-ready"),
    path("studio-projects/<int:project_id>/checkout/", CustomerStudioCheckoutAPIView.as_view(), name="studio-checkout"),
    path("media/<int:asset_id>/", CustomerPrivateMediaAPIView.as_view(), name="private-media"),
    path("cart/", CustomerCartAPIView.as_view(), name="cart"),
    path("cart/items/", CustomerCartItemCreateAPIView.as_view(), name="cart-item-create"),
    path("cart/items/<int:item_id>/", CustomerCartItemDetailAPIView.as_view(), name="cart-item-detail"),
    path("cart/checkout/", CustomerCartCheckoutAPIView.as_view(), name="cart-checkout"),
    path("checkouts/<int:checkout_id>/", CustomerCheckoutDetailAPIView.as_view(), name="checkout-detail"),
    path("checkouts/<int:checkout_id>/place/", CustomerPlaceCheckoutAPIView.as_view(), name="checkout-place"),
    path("payment-options/", CustomerPaymentOptionsAPIView.as_view(), name="payment-options"),
    path("purchases/", CustomerPurchaseListAPIView.as_view(), name="purchases"),
    path("purchases/<uuid:purchase_reference>/", CustomerPurchaseDetailAPIView.as_view(), name="purchase-detail"),
    path("notifications/", CustomerNotificationListAPIView.as_view(), name="notifications"),
    path("notifications/preferences/", CustomerNotificationPreferenceAPIView.as_view(), name="notification-preferences"),
    path("notifications/read-all/", CustomerNotificationReadAllAPIView.as_view(), name="notification-read-all"),
    path("notifications/<int:notification_id>/read/", CustomerNotificationReadAPIView.as_view(), name="notification-read"),
]
